export const INIT_PROJECTLIST="PROJECT.INIT_PROJECTLIST";
export const INIT_PROJECTDETAILS="PROJECT.INIT_PROJECTDETAILS";
export const INIT_EDITEDPROJECTDETAILS="PROJECT.INIT_EDITEDPROJECTDETAILS";
export const LOADING="STATES.LOADING";
export const ERROR="STATES.ERROR";
