export const INIT_EMPLOYEELIST="EMPLOYEE.INIT_EMPLOYEELIST";
export const INIT_EMPLOYEEDETAILS="EMPLOYEE.INIT_EMPLOYEEDETAILS";
export const INIT_EDITEDEMPLOYEEDETAILS="EMPLOYEE.INIT_EDITEDEMPLOYEEDETAILS";
export const LOADING="EMPLOYEE.LOADING";
export const RESULT="EMPLOYEE.RESULT";
