export const INIT_EMPLOYEELIST="EMPLOYEE.INIT_EMPLOYEELIST";
export const INIT_EMPLOYEEDETAILS="EMPLOYEE.INIT_EMPLOYEEDETAILS";
export const INIT_EMPLOYEEPROJECTLIST="EMPLOYEE.INIT_EMPLOYEEPROJECTLIST";
export const init_employeePermanentAddress="EMPLOYEE.INIT_EMPLOYEEPERMENENTADDRESS";
export const init_employeeCurrentAddress="EMPLOYEE.INIT_EMPLOYEECURRENTADDRESS";
export const LOADING="EMPLOYEE.LOADING";
export const RESULT="EMPLOYEE.RESULT";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";
export const INIT_PROJECTLIST="PROJECT.INIT_PROJECTLIST";
export const INIT_PROJECTDETAILS="PROJECT.INIT_PROJECTDETAILS";
export const INIT_EDITEDPROJECTDETAILS="PROJECT.INIT_EDITEDPROJECTDETAILS";
export const ERROR="STATES.ERROR";


